/* !!! Do not manually modify this file in the production stage !!!
 * This file is automatically created by MakeResBin.exe,
 * and used in the production stage.*/

#ifndef __RES_H_
#define __RES_H_

#define         RES_AUDIOPLAY0_BK       	0
#define         RES_AUDIOPLAY_BK        	1
#define         RES_CAM_INIT            	2
#define         RES_EBOOK_FONT20        	3
#define         RES_FRAME0              	4
#define         RES_FRAME1              	5
#define         RES_FRAME2              	6
#define         RES_FRAME3              	7
#define         RES_FRAME4              	8
#define         RES_FRAME5              	9
#define         RES_FRAME6              	10
#define         RES_FRAME7              	11
#define         RES_FRAME8              	12
#define         RES_GAMEMENU_BK         	13
#define         RES_GAMEMENU_BOLL       	14
#define         RES_GAMEMENU_MAZE       	15
#define         RES_GAMEMENU_PLANE      	16
#define         RES_GAMEMENU_PUSHBOX    	17
#define         RES_GAMEMENU_RB         	18
#define         RES_GAMEMENU_SNAKE      	19
#define         RES_GAME_BLOCK_BK0      	20
#define         RES_GAME_BLOCK_BK1      	21
#define         RES_GAME_BLOCK_BK2      	22
#define         RES_GAME_BLOCK_BK3      	23
#define         RES_GAME_BLOCK_ICON     	24
#define         RES_GAME_BLOCK_KNOCK    	25
#define         RES_GAME_BLOCK_MAP      	26
#define         RES_GAME_MAZE_MAP       	27
#define         RES_GAME_PLANE_AUDIO    	28
#define         RES_GAME_PLANE_ICON     	29
#define         RES_GAME_SNAKE_ICON     	30
#define         RES_GAME_SOKOBAN_ICON   	31
#define         RES_GAME_SOKOBAN_MAP    	32
#define         RES_GAME_TETRIS_BK      	33
#define         RES_GAME_TETRIS_ICON    	34
#define         RES_ICONSETTINGMENU     	35
#define         RES_ICON_BACKWARD       	36
#define         RES_ICON_FORWARD        	37
#define         RES_MAIN_BK             	38
#define         RES_MAIN_GAME_BK        	39
#define         RES_MAIN_MP3_BK         	40
#define         RES_MAIN_PHOTO_BK       	41
#define         RES_MAIN_PLAYBACK_BK    	42
#define         RES_MAIN_SETTING_BK     	43
#define         RES_MAIN_VIDEO_BK       	44
#define         RES_MP3FONT             	45
#define         RES_MUSIC_KEY_SOUND     	46
#define         RES_MUSIC_PHOTO_FOCUS   	47
#define         RES_MUSIC_PHOTO_TIME    	48
#define         RES_MUSIC_POWER_OFF     	49
#define         RES_MUSIC_POWER_ON      	50
#define         RES_MUSIC_TAKE_PHOTO    	51
#define         RES_NUM_0               	52
#define         RES_NUM_1               	53
#define         RES_NUM_2               	54
#define         RES_NUM_3               	55
#define         RES_NUM_4               	56
#define         RES_NUM_5               	57
#define         RES_NUM_6               	58
#define         RES_NUM_7               	59
#define         RES_NUM_8               	60
#define         RES_NUM_9               	61
#define         RES_NUM_BLANK           	62
#define         RES_NUM_COLON           	63
#define         RES_NUM_SLASH           	64
#define         RES_OEM2UNI936          	65
#define         RES_OSD_SOURCE          	66
#define         RES_PALETTE             	67
#define         RES_PALETTE_GAME        	68
#define         RES_POWER_OFF           	69
#define         RES_POWER_ON            	70
#define         RES_RESFONT             	71
#define         RES_RESFONTIDX          	72
#define         RES_SETTINGMENU_BK      	73
#define         RES_STR_VERSION         	74
#define         RES_UNI2OEM936          	75
#define         RES_USBBAT_10           	76
#define         RES_USBBAT_100          	77
#define         RES_USBBAT_20           	78
#define         RES_USBBAT_30           	79
#define         RES_USBBAT_40           	80
#define         RES_USBBAT_50           	81
#define         RES_USBBAT_60           	82
#define         RES_USBBAT_70           	83
#define         RES_USBBAT_80           	84
#define         RES_USBBAT_90           	85
#define         RES_USBMODE_MSC         	86
#define         RES_USBMODE_PCCAM       	87

#endif
